### ISSUE TITLE
Nautilus bottom "status" info overlapping row file information

### ISSUE THREAD

**Issue by jantomicky** [Chrysostomus/adwaita-maia#4]
When a file is selected, the "status" info covers up / overlaps with the file info on that row (see screenshot).

![2020-11-17_19-55-09](https://user-images.githubusercontent.com/41518085/99434866-98383200-290f-11eb-830c-1f813431decc.png)

**Comment by Chrysostomus** [comment]
Thank you for reporting. We are in the process of rewriting this theme, so we'll have to re-evaluate the situation in a few weeks when we see whether or not it persists.

**Comment by jantomicky** [comment]
That's great, thank you for responsing so quicky! Just curious, are there many changes in this theme as opposed to regular Adwaita?

My understanding was that this was just Adwaita, only built with a different color palette. But that's just my assumption as I didn't read through the code.

**Comment by Chrysostomus** [comment]
It's just a adwaita with blue replaced with green.

**Comment by jantomicky** [comment]
Fixed with the latest update, thanks.
